# WorkflowNo_0
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_0
doc: A workflow including the tool(s) create_project, create_structure_genericbulk, create_job_gpaw, create_job_murn, run_job_murn, get_property_bulkmodulus.

inputs:
  input_1:
    type: File
    format: "unknown"
steps:
  create_project_01:
    run: add-path-to-the-implementation/create_project.cwl 
    in: []
    out: [create_project_out_1]
  create_structure_genericbulk_02:
    run: add-path-to-the-implementation/create_structure_genericbulk.cwl 
    in:
      create_structure_genericbulk_in_1: create_project_01/create_project_out_1
      create_structure_genericbulk_in_2: input_1
    out: [create_structure_genericbulk_out_1]
  create_job_gpaw_03:
    run: add-path-to-the-implementation/create_job_gpaw.cwl 
    in:
      create_job_gpaw_in_1: create_project_01/create_project_out_1
      create_job_gpaw_in_2: create_structure_genericbulk_02/create_structure_genericbulk_out_1
    out: [create_job_gpaw_out_1]
  create_job_murn_04:
    run: add-path-to-the-implementation/create_job_murn.cwl 
    in:
      create_job_murn_in_1: create_project_01/create_project_out_1
      create_job_murn_in_2: create_job_gpaw_03/create_job_gpaw_out_1
    out: [create_job_murn_out_1]
  run_job_murn_05:
    run: add-path-to-the-implementation/run_job_murn.cwl 
    in:
      run_job_murn_in_1: create_job_murn_04/create_job_murn_out_1
    out: [run_job_murn_out_1]
  get_property_bulkmodulus_06:
    run: add-path-to-the-implementation/get_property_bulkmodulus.cwl 
    in:
      get_property_bulkmodulus_in_1: run_job_murn_05/run_job_murn_out_1
    out: [get_property_bulkmodulus_out_1]
outputs:
  output_1:
    type: File
    format: "unknown"
    outputSource: get_property_bulkmodulus_06/get_property_bulkmodulus_out_1
