# WorkflowNo_04
# This workflow is generated by APE (https://github.com/workflomics/ape).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_04
doc: A workflow including the tool(s) create_project, create_structure_bulk, create_vacancy_Al, relax_structure, calculate_energy_1Vac, calculate_energy_no_defect, calculate_defect_formation_energy, calc_chemical_potential_A, calc_defect_concentration.

inputs:
  input_1:
    type: File
    format: "unknown"
steps:
  create_project_01:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#create_project.cwl 
    in: []
    out: [create_project_out_1]
  create_structure_bulk_02:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#create_structure_bulk.cwl 
    in:
      create_structure_bulk_in_1: create_project_01/create_project_out_1
      create_structure_bulk_in_2: input_1
    out: [create_structure_bulk_out_1]
  create_vacancy_Al_03:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#create_vacancy_Al.cwl 
    in:
      create_vacancy_Al_in_1: create_structure_bulk_02/create_structure_bulk_out_1
    out: [create_vacancy_Al_out_1]
  relax_structure_04:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#relax_structure.cwl 
    in:
      relax_structure_in_1: create_vacancy_Al_03/create_vacancy_Al_out_1
    out: [relax_structure_out_1]
  calculate_energy_1Vac_05:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#calculate_energy_1Vac.cwl 
    in:
      calculate_energy_1Vac_in_1: relax_structure_04/relax_structure_out_1
    out: [calculate_energy_1Vac_out_1]
  calculate_energy_no_defect_06:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#calculate_energy_no_defect.cwl 
    in:
      calculate_energy_no_defect_in_1: create_structure_bulk_02/create_structure_bulk_out_1
    out: [calculate_energy_no_defect_out_1]
  calculate_defect_formation_energy_07:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#calculate_energy_1AS_1Vac_AB[tool].cwl 
    in:
      calculate_defect_formation_energy_in_1: calculate_energy_1Vac_05/calculate_energy_1Vac_out_1
      calculate_defect_formation_energy_in_2: calculate_energy_no_defect_06/calculate_energy_no_defect_out_1
    out: [calculate_defect_formation_energy_out_1]
  calc_chemical_potential_A_08:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#calc_chemical_potential_A.cwl 
    in:
      calc_chemical_potential_A_in_1: input_1
    out: [calc_chemical_potential_A_out_1]
  calc_defect_concentration_09:
    run: add-path-to-the-implementation/http://www.semanticweb.org/materials_science#calc_defect_concentration.cwl 
    in:
      calc_defect_concentration_in_1: calculate_defect_formation_energy_07/calculate_defect_formation_energy_out_1
      calc_defect_concentration_in_2: calc_chemical_potential_A_08/calc_chemical_potential_A_out_1
    out: [calc_defect_concentration_out_1]
outputs:
  output_1:
    type: File
    format: "unknown"
    outputSource: calc_defect_concentration_09/calc_defect_concentration_out_1
