#!/bin/bash
# WorkflowNo_01
# This workflow is generated by APE (https://github.com/workflomics/ape).
if [ $# -ne 3 ]
	then
		echo "3 argument(s) expected."
		exit
fi
node1149868370=$1
node-181910821=$2
node990215733=$3

# Error: Tool 'get_speed' is missing the execution code. Skipping.
# Error: Tool 'get_kinetic_energy' is missing the execution code. Skipping.
echo "1. output is: $node447785762"